image: gitlabdocker.rcxt.de/builder/scala:v3-21

variables:
  SBT_OPTS: "-Dsbt.ivy.home=$PWD/cache/ivy -Divy.home=$PWD/cache/ivy -Dsbt.global.base=$PWD/cache/sbt -Dsbt.boot.directory=$PWD/cache/sbt_boot  -Dsbt.coursier.home=$PWD/cache/coursier"

cache:
  key: "SBT_CACHE"
  untracked: false
  paths:
    - "cache"

stages:
  - build

test:
  stage: build
  script:
    - sbt clean test
