package kreuzberg.examples.showcase.todo

import io.circe.Codec
import kreuzberg.rpc.ApiName

/**
 * Sample API. The client code will be generated by a macro. On Server side, it will be implemented.
 */
@ApiName("todo")
trait TodoApi[F[_]] {

  /** List current items. */
  def listItems(): F[ListItemResponse]

  /** Add one item. */
  def addItem(item: String): F[Unit]

}

case class ListItemResponse(
    items: Seq[String],
    statusCode: Int
) derives Codec.AsObject
