package kreuzberg.examples.showcase.todo

/**
 * Sample API. The client code will be generated by a macro. On Server side, it will be implemented.
 */
trait TodoApi[F[_]] {

  /** List current items. */
  def listItems(): F[Seq[String]]

  /** Add one item. */
  def addItem(item: String): F[Unit]

}
