name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Import GPG key
        run: |
          echo "$PGP_SECRET" | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Publish to Sonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          JAVA_OPTS: -Xms2048M -Xmx4096M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
          JVM_OPTS: -Xms2048M -Xmx4096M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
        run: |
          mkdir -p ~/.sbt/1.0
          echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"central.sonatype.com\", sys.env.getOrElse(\"SONATYPE_USERNAME\", \"\"), sys.env.getOrElse(\"SONATYPE_PASSWORD\", \"\"))" > ~/.sbt/1.0/sonatype.sbt
          sbt clean publishSigned sonatypeBundleRelease
